// DDR_PHY_CTRL APB4 Slave Register Module
// Auto-generated by LazySOC - DO NOT EDIT
//
// Address Map:
//   0x0000 : PHY_CONFIG (RW)
//   0x0004 : PHY_STATUS (RO)

module ddr_phy_ctrl_apb_slave (
    // Clock and Reset
    input  logic        pclk,
    input  logic        presetn,

    // APB4 Slave Interface
    input  logic [31:0] paddr,
    input  logic        psel,
    input  logic        penable,
    input  logic        pwrite,
    input  logic [31:0] pwdata,
    input  logic [3:0]  pstrb,
    input  logic [2:0]  pprot,

    output logic        pready,
    output logic [31:0] prdata,
    output logic        pslverr
);

  // ---------------------------------------------------------------------------
  // Local Parameters - Register Offsets
  // ---------------------------------------------------------------------------
  localparam logic [31:0] OFFSET_PHY_CONFIG = 32'h00000000;
  localparam logic [31:0] OFFSET_PHY_STATUS = 32'h00000004;

  // ---------------------------------------------------------------------------
  // Register Declarations
  // ---------------------------------------------------------------------------
  logic [31:0] reg_phy_config;

  // ---------------------------------------------------------------------------
  // Internal Signals
  // ---------------------------------------------------------------------------
  logic [31:0] addr_offset;
  logic        wr_en;
  logic        rd_en;
  logic        decode_error;
  logic        write_to_ro_error;
  logic [31:0] next_prdata;
  logic        next_pslverr;

  // Address offset within the block (mask to relevant bits)
  assign addr_offset = paddr & 32'h0000FFFF;

  // Write enable: psel && penable && pwrite (Access Phase)
  assign wr_en = psel & penable & pwrite;

  // Read enable: psel && !pwrite (Setup Phase, data prepared for Access Phase)
  assign rd_en = psel & ~pwrite;

  // ---------------------------------------------------------------------------
  // Address Decode Logic (Combinational)
  // ---------------------------------------------------------------------------
  always_comb begin : addr_decode
    decode_error = 1'b0;
    write_to_ro_error = 1'b0;

    if (psel) begin
      case (addr_offset)
        OFFSET_PHY_CONFIG: begin
        end
        OFFSET_PHY_STATUS: begin
          if (pwrite) begin
            write_to_ro_error = 1'b1;
          end
        end
        default: begin
          decode_error = 1'b1;
        end
      endcase
    end
  end

  // ---------------------------------------------------------------------------
  // Write Logic (Sequential)
  // ---------------------------------------------------------------------------
  always_ff @(posedge pclk or negedge presetn) begin : write_proc
    if (!presetn) begin
      reg_phy_config <= 32'h0;
    end else if (wr_en && !decode_error && !write_to_ro_error) begin
      case (addr_offset)
        OFFSET_PHY_CONFIG: begin
          // Byte-enable write
          if (pstrb[0]) reg_phy_config[7:0]   <= pwdata[7:0];
          if (pstrb[1]) reg_phy_config[15:8]  <= pwdata[15:8];
          if (pstrb[2]) reg_phy_config[23:16] <= pwdata[23:16];
          if (pstrb[3]) reg_phy_config[31:24] <= pwdata[31:24];
        end
        default: ; // No action
      endcase
    end
  end

  // ---------------------------------------------------------------------------
  // Read Logic (Combinational - generates next_prdata)
  // ---------------------------------------------------------------------------
  always_comb begin : read_comb
    next_prdata = 32'h0;
    next_pslverr = 1'b0;

    if (psel && penable) begin
      // Error conditions
      if (decode_error || write_to_ro_error) begin
        next_pslverr = 1'b1;
        next_prdata = 32'h0;
      end else if (!pwrite) begin
        // Read operation
        case (addr_offset)
          OFFSET_PHY_CONFIG: next_prdata = reg_phy_config;
          OFFSET_PHY_STATUS: next_prdata = 32'h0; // TODO: Connect to hardware status
          default: next_prdata = 32'h0;
        endcase
      end
    end
  end

  // ---------------------------------------------------------------------------
  // Registered Output (Sequential)
  // ---------------------------------------------------------------------------
  always_ff @(posedge pclk or negedge presetn) begin : output_reg
    if (!presetn) begin
      prdata  <= 32'h0;
      pslverr <= 1'b0;
    end else begin
      prdata  <= next_prdata;
      pslverr <= next_pslverr;
    end
  end

  // PREADY always high for simple APB slave (no wait states)
  assign pready = 1'b1;

  // ---------------------------------------------------------------------------
  // Unused signal
  // ---------------------------------------------------------------------------
  // pprot is not used in this simple implementation
  logic unused_pprot;
  assign unused_pprot = |pprot;

endmodule : ddr_phy_ctrl_apb_slave