// DDR_PHY_CTRL Register Package
// Auto-generated by LazySOC - DO NOT EDIT

package ddr_phy_ctrl_pkg;

  // Base Address
  localparam logic [31:0] DDR_PHY_CTRL_BASE_ADDR = 32'h40000000;

  // Register Offsets
  localparam logic [31:0] DDR_PHY_CTRL_PHY_CONFIG_OFFSET = 32'h00000000;
  localparam logic [31:0] DDR_PHY_CTRL_PHY_STATUS_OFFSET = 32'h00000004;

  // Field Definitions
  // PHY_CONFIG.enable
  localparam int PHY_CONFIG_ENABLE_LSB = 0;
  localparam int PHY_CONFIG_ENABLE_MSB = 0;
  localparam int PHY_CONFIG_ENABLE_WIDTH = 1;
  localparam logic [31:0] PHY_CONFIG_ENABLE_MASK = 32'h00000001;
  // PHY_CONFIG.calibration_mode
  localparam int PHY_CONFIG_CALIBRATION_MODE_LSB = 1;
  localparam int PHY_CONFIG_CALIBRATION_MODE_MSB = 3;
  localparam int PHY_CONFIG_CALIBRATION_MODE_WIDTH = 3;
  localparam logic [31:0] PHY_CONFIG_CALIBRATION_MODE_MASK = 32'h0000000E;
  // PHY_STATUS.lock_status
  localparam int PHY_STATUS_LOCK_STATUS_LSB = 0;
  localparam int PHY_STATUS_LOCK_STATUS_MSB = 0;
  localparam int PHY_STATUS_LOCK_STATUS_WIDTH = 1;
  localparam logic [31:0] PHY_STATUS_LOCK_STATUS_MASK = 32'h00000001;
  // PHY_STATUS.error_count
  localparam int PHY_STATUS_ERROR_COUNT_LSB = 8;
  localparam int PHY_STATUS_ERROR_COUNT_MSB = 15;
  localparam int PHY_STATUS_ERROR_COUNT_WIDTH = 8;
  localparam logic [31:0] PHY_STATUS_ERROR_COUNT_MASK = 32'h0000FF00;

endpackage : ddr_phy_ctrl_pkg