/**
 * DDR_PHY_CTRL Register Definitions
 * Auto-generated by LazySOC - DO NOT EDIT
 */

#ifndef DDR_PHY_CTRL_REGS_H
#define DDR_PHY_CTRL_REGS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Base Address */
#define DDR_PHY_CTRL_BASE_ADDR  (0x40000000UL)

/* Register Offsets */
#define DDR_PHY_CTRL_PHY_CONFIG_OFFSET  (0x0UL)
#define DDR_PHY_CTRL_PHY_STATUS_OFFSET  (0x4UL)

/* Field Masks and Shifts */
#define PHY_CONFIG_ENABLE_SHIFT  (0U)
#define PHY_CONFIG_ENABLE_MASK   (0x1UL)
#define PHY_CONFIG_ENABLE_WIDTH  (1U)
#define PHY_CONFIG_CALIBRATION_MODE_SHIFT  (1U)
#define PHY_CONFIG_CALIBRATION_MODE_MASK   (0xEUL)
#define PHY_CONFIG_CALIBRATION_MODE_WIDTH  (3U)
#define PHY_STATUS_LOCK_STATUS_SHIFT  (0U)
#define PHY_STATUS_LOCK_STATUS_MASK   (0x1UL)
#define PHY_STATUS_LOCK_STATUS_WIDTH  (1U)
#define PHY_STATUS_ERROR_COUNT_SHIFT  (8U)
#define PHY_STATUS_ERROR_COUNT_MASK   (0xFF00UL)
#define PHY_STATUS_ERROR_COUNT_WIDTH  (8U)

/* Register Structure */
typedef struct {
    volatile uint32_t PHY_CONFIG;  /* 0x0 - RW - PHY Configuration Register */
    volatile uint32_t PHY_STATUS;  /* 0x4 - RO - PHY Status Register */
} DDR_PHY_CTRL_TypeDef;

#define DDR_PHY_CTRL  ((DDR_PHY_CTRL_TypeDef *)DDR_PHY_CTRL_BASE_ADDR)

#ifdef __cplusplus
}
#endif

#endif /* DDR_PHY_CTRL_REGS_H */