"""Markdown 文档生成器"""

from pathlib import Path

from lazysoc.parser import Block, Field, Register


def _format_bits(field: Field) -> str:
    """格式化 bit 范围显示"""
    if field.msb == field.lsb:
        return f"[{field.msb}]"
    return f"[{field.msb}:{field.lsb}]"


def _safe_desc(desc: str) -> str:
    """处理空描述"""
    return desc if desc else "-"


def _generate_address_map_table(block: Block) -> str:
    """生成地址映射概览表"""
    lines = [
        "| Register | Offset | Access | Description |",
        "|:---------|:-------|:------:|:------------|",
    ]
    for reg in block.registers:
        desc = _safe_desc(reg.description)
        lines.append(f"| {reg.name} | {reg.offset_hex} | {reg.access} | {desc} |")
    return "\n".join(lines)


def _generate_field_table(reg: Register) -> str:
    """生成单个寄存器的位域表"""
    lines = [
        "| Bits | Name | Access | Reset | Description |",
        "|:-----|:-----|:------:|:------|:------------|",
    ]
    # 按 MSB 降序排列字段
    sorted_fields = sorted(reg.fields, key=lambda f: f.msb, reverse=True)
    for field in sorted_fields:
        bits = _format_bits(field)
        desc = _safe_desc(field.description)
        lines.append(
            f"| {bits} | {field.name} | {reg.access} | {field.reset_hex} | {desc} |"
        )
    return "\n".join(lines)


def _generate_register_details(block: Block) -> str:
    """生成寄存器详细定义"""
    sections = []
    for reg in block.registers:
        section_lines = [
            f"## {reg.name} ({reg.offset_hex})",
            "",
            f"**Access:** {reg.access}",
            "",
            f"**Description:** {_safe_desc(reg.description)}",
            "",
        ]
        if reg.fields:
            section_lines.append("### Bit Fields")
            section_lines.append("")
            section_lines.append(_generate_field_table(reg))
        else:
            section_lines.append("*No fields defined.*")
        sections.append("\n".join(section_lines))
    return "\n\n---\n\n".join(sections)


def generate_markdown(block: Block) -> str:
    """
    生成完整的 Markdown 文档

    Args:
        block: 解析后的 Block 对象

    Returns:
        格式化的 Markdown 字符串
    """
    lines = [
        f"# {block.name} Register Reference",
        "",
        f"> Base Address: `{block.base_address_hex}`",
        "",
    ]

    if block.description:
        lines.extend([block.description, ""])

    lines.extend([
        "## Address Map",
        "",
        _generate_address_map_table(block),
        "",
        "## Register Details",
        "",
        _generate_register_details(block),
        "",
        "---",
        "",
        "*Auto-generated by LazySOC*",
    ])

    return "\n".join(lines)


def write_markdown(block: Block, output_path: Path) -> None:
    """生成并写入 Markdown 文档"""
    content = generate_markdown(block)
    output_path.write_text(content, encoding="utf-8")
